name: 'mailchimp'
version: '1.0.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:         
    - "target"
    - "dbt_modules"

models:
    mailchimp:
        vars:
            campaign:
            campaign_recipient:
            campaign_recipient_activity:
            list:
            member:
            unsubscribe:
